apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "comments-api.fullname" . }}
  labels:
    {{- include "comments-api.labels" . | nindent 4 }}
data:
  DB_POOL_SIZE: {{ .Values.database.poolSize | quote }}
  DB_MAX_OVERFLOW: {{ .Values.database.maxOverflow | quote }}
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
